# This will populate the metrics in all the tiers, under this path(not recommended)
# metricPrefix: "Custom Metrics|Prometheus"
# The following prefix will populate the metrics under one tier
metricPrefix: "Server|Component:<TIER NAME OR TIER ID>|Custom Metrics|Prometheus"

# Add your list of Prometheus servers here.
servers:
  - name: "Server1"          # Required.
    host: "localhost"        # Hostname to connect to. Required.
    port: "6379"             # Port number to connect to. Required.
    path: "/metrics"         # URI to the metrics endpoint. Optional (default: "/metrics").
    username: ""             # Username to send in HTTP basic auth. Optional (default: no auth).
    password: ""             # Password to send in HTTP basic auth. Optional (default: no auth).
    useSSL: false            # Set to true if endpoint serves HTTPS. Optional (default: false).

# Encryption key for passwords (see docs).
encryptionKey: ""

# Each server instance needs 2 threads, one for the server instance itself,
# and one for the HTTP call to the Prometheus server. Please change the value
# accordingly (based on the number of server instances you are monitoring).
numberOfThreads: 20

#                                      List of metrics
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#Glossary of terms(These terms are used as properties for each metric):
#   alias
#   aggregationType
#   timeRollUpType
#   clusterRollUpType                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
#   multiplier -->not for derived metrics
#   convert --> not for derived metrics
#   delta --> not for derived metrics
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Sample configuration for Node Exporter
metrics:
    Golang Runtime:
        - go_gc_duration_seconds
        - go_memstats_alloc_bytes
            aggregationType: OBSERVATION
            timeRollUpType: CURRENT
            clusterRollUpType: INDIVIDUAL
        - go_memstats_heap_alloc_bytes
        - go_memstats_heap_objects
        - go_memstats_heap_sys_bytes
        - go_threads
    Host Metrics:
        CPU:
            - node_cpu_frequency_min_hertz
            - node_cpu_frequency_max_hertz
            - node_cpu_guest_seconds_total
            - node_cpu_seconds_total
        Disks:
            - node_disk_io_time_seconds_total
            - node_disk_io_time_weighted_seconds_total
            - node_disk_read_bytes_total
            - node_disk_read_time_seconds_total
            - node_disk_reads_completed_total
            - node_disk_written_bytes_total
            - node_disk_write_time_seconds_total
            - node_disk_writes_completed_total
        Volumes:
            - node_filesystem_avail_bytes
            - node_filesystem_device_error
            - node_filesystem_files
            - node_filesystem_files_free
            - node_filesystem_free_bytes
            - node_filesystem_size_bytes
